paperwork:
  image: paperwork2
  links:
    - paperwork-db:paperwork-db
  command: /app/docker-runner.sh

paperwork-db:
  image: mariadb:10
  volumes:
    - pwdb:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=paperwork
    - MYSQL_DATABASE=paperwork
    - MYSQL_USER=paperwork
    - MYSQL_PASSWORD=paperwork
